#!/bin/bash

# See /usr/share/doc/bash-doc/examples in the bash-doc package.

export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\W\[\033[m\]\$"

export LSCOLORS="di=1;36;40:ln=1;31;40:so=32:pi=33:ex=35;40:bd=37;40:cd=37;42:su=35;47:sg=35;47:tw=1;36;44:ow=1;36;44"

export VISUAL=vim
export EDITOR="$VISUAL"

# alias definitions.

if [ -f ~/.bash_aliases_ag ]; then
    . ~/.bash_aliases_ag   
fi

# set PATH so it includes user's private bin if it exists
if [ -d ~/bin_ag ] ; then
    PATH=~/bin_ag:"${PATH}"
fi

## enable programmable completion features
#
#if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
#    . /etc/bash_completion
#fi

